import { ProductosInterface } from "../app/features/listado-productos/productos.interface";

export const products: ProductosInterface[] = [
{
    id: 1,
    name: 'Notebook Lenovo ThinkPad',
    description: 'Notebook empresarial con alto rendimiento',
    price: 1200000,
    stock: 5,
    category: 'Tecnología',
    active: true,
  },
  {
    id: 2,
    name: 'Mouse Logitech MX Master 3',
    description: 'Mouse inalámbrico ergonómico',
    price: 180000,
    stock: 12,
    category: 'Accesorios',
    active: true,
  },
  {
    id: 3,
    name: 'Teclado Mecánico Redragon',
    description: 'Teclado mecánico RGB switches blue',
    price: 95000,
    stock: 8,
    category: 'Accesorios',
    active: false,
  },
  {
    id: 4,
    name: 'Monitor Samsung 27"',
    description: 'Monitor Full HD 75Hz',
    price: 320000,
    stock: 6,
    category: 'Tecnología',
    active: true,
  },
  {
    id: 5,
    name: 'Auriculares Sony WH-1000XM5',
    description: 'Auriculares con cancelación de ruido',
    price: 680000,
    stock: 4,
    category: 'Audio',
    active: false,
  },
  {
    id: 6,
    name: 'Webcam Logitech C920',
    description: 'Webcam Full HD para streaming',
    price: 210000,
    stock: 10,
    category: 'Video',
    active: true,
  },
  {
    id: 7,
    name: 'Disco SSD Kingston 1TB',
    description: 'SSD SATA alta velocidad',
    price: 160000,
    stock: 15,
    category: 'Almacenamiento',
    active: true,
  },
  {
    id: 8,
    name: 'Silla Gamer Corsair',
    description: 'Silla ergonómica para largas jornadas',
    price: 450000,
    stock: 3,
    category: 'Muebles',
    active: true,
  },
  {
    id: 9,
    name: 'Tablet Samsung Galaxy Tab',
    description: 'Tablet Android 10 pulgadas',
    price: 520000,
    stock: 7,
    category: 'Tecnología',
    active: true,
  },
  {
    id: 10,
    name: 'Cargador USB-C 65W',
    description: 'Cargador rápido universal',
    price: 65000,
    stock: 20,
    category: 'Accesorios',
    active: true,
  }
]


